packages:
  - apps/*
  - packages/*
allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  sharp: true
  '@prisma/engines': true
  prisma: true
  argon2: true
overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1
