// Fictional Vietnamese bistro data. Prices and quantities are demo assumptions, not a real restaurant's menu.
export const demoStaff = [
  ['quyettruong05', 'Lưu Quyết Trường', 'ADMIN'],
  ['pv001', 'Nguyễn Minh Anh', 'STAFF'],
  ['pv002', 'Nguyễn Minh Anh', 'STAFF'],
  ['pv003', 'Trần Ngọc Lan', 'STAFF'],
  ['pv004', 'Lê Hoàng Nam', 'STAFF'],
  ['bep001', 'Phạm Anh Tuấn', 'KITCHEN'],
  ['bep002', 'Lê Thu Hoa', 'KITCHEN'],
  ['bep003', 'Nguyễn Minh Anh', 'KITCHEN'],
] as const;
export const demoCategories = [
  ['KHAI-VI', 'Khai vị', 'Món nhỏ, niềm vui lớn', 'starter'],
  ['MON-CHINH', 'Cơm & bún phở', 'Hương vị thân quen cho mỗi ngày', 'rice'],
  ['MON-NUONG', 'Món nướng', 'Thơm lừng từ căn bếp', 'grill'],
  ['CANH-LAU', 'Canh & lẩu', 'Cùng nhau chia sẻ món nóng', 'soup'],
  ['DO-UONG', 'Thức uống', 'Tươi mát, pha chế tại quầy', 'drink'],
  ['TRANG-MIENG', 'Tráng miệng', 'Một kết thúc ngọt ngào', 'dessert'],
] as const;
// code, name, unit, opening quantity, unit cost VND, minimum stock; measured in the stated base unit.
export const demoIngredients = [
  ['RICE', 'Gạo tấm', 'KG', 45, 18000, 8],
  ['CHICKEN', 'Thịt gà', 'KG', 24, 98000, 5],
  ['BEEF', 'Thịt bò', 'KG', 18, 245000, 4],
  ['PORK', 'Thịt heo', 'KG', 28, 135000, 5],
  ['SHRIMP', 'Tôm', 'KG', 12, 210000, 3],
  ['FISH', 'Cá phi lê', 'KG', 15, 125000, 3],
  ['NOODLE', 'Bún tươi', 'KG', 22, 28000, 4],
  ['PHO', 'Bánh phở', 'KG', 20, 32000, 4],
  ['HERBS', 'Rau thơm', 'KG', 8, 45000, 2],
  ['VEGETABLE', 'Rau theo mùa', 'KG', 25, 28000, 5],
  ['MUSHROOM', 'Nấm tươi', 'KG', 10, 65000, 2],
  ['RICEPAPER', 'Bánh tráng', 'KG', 6, 48000, 1],
  ['OIL', 'Dầu ăn', 'L', 18, 45000, 3],
  ['SAUCE', 'Nước mắm', 'L', 12, 35000, 2],
  ['SUGAR', 'Đường', 'KG', 15, 23000, 3],
  ['TEA', 'Trà ô long', 'KG', 3, 210000, 0.5],
  ['COFFEE', 'Cà phê rang xay', 'KG', 4, 220000, 1],
  ['MILK', 'Sữa đặc', 'KG', 8, 65000, 2],
  ['KUMQUAT', 'Tắc tươi', 'KG', 6, 32000, 1],
  ['HONEY', 'Mật ong', 'KG', 4, 150000, 1],
  ['LEMONGRASS', 'Sả', 'KG', 5, 25000, 1],
  ['LEMONLEAF', 'Lá chanh / lá é', 'KG', 2, 65000, 0.5],
  ['HERBAL', 'Thảo mộc nấu sâm', 'KG', 2, 120000, 0.5],
  ['YOGURT', 'Sữa chua', 'KG', 8, 50000, 2],
  ['FRUIT', 'Trái cây theo mùa', 'KG', 15, 45000, 3],
  ['CREAM', 'Kem sữa', 'L', 6, 110000, 1],
  ['ALMOND', 'Hạnh nhân', 'KG', 2, 220000, 0.5],
  ['GELATIN', 'Gelatin', 'KG', 1, 250000, 0.2],
  ['BROTH', 'Nước dùng nền', 'L', 55, 18000, 10],
  ['TOFU', 'Đậu hũ', 'KG', 8, 25000, 2],
  ['EGG', 'Trứng gà', 'PCS', 60, 3000, 12],
  ['PEPPER', 'Tiêu đen', 'KG', 1, 180000, 0.2],
] as const;
type Dish = {
  code: string;
  category: number;
  name: string;
  price: number;
  description: string;
  recipe: Record<string, number>;
};
export const demoMenu: Dish[] = [
  {
    code: 'KHAI-01',
    category: 0,
    name: 'Gỏi cuốn tôm thịt',
    price: 45000,
    description: 'Ba cuốn tươi với tôm, thịt heo, bún và rau thơm. Dùng cùng nước chấm riêng.',
    recipe: { SHRIMP: 0.06, PORK: 0.04, NOODLE: 0.07, RICEPAPER: 0.025, HERBS: 0.03, SAUCE: 0.02 },
  },
  {
    code: 'KHAI-02',
    category: 0,
    name: 'Chả giò giòn',
    price: 55000,
    description: 'Bốn cuốn chả giò nhân thịt và nấm, chiên vàng. Phù hợp để chia sẻ.',
    recipe: { PORK: 0.09, MUSHROOM: 0.04, RICEPAPER: 0.04, OIL: 0.025, VEGETABLE: 0.03 },
  },
  {
    code: 'KHAI-03',
    category: 0,
    name: 'Gỏi gà rau thơm',
    price: 79000,
    description: 'Gà xé trộn rau tươi, nước mắm chua ngọt và rau thơm.',
    recipe: { CHICKEN: 0.15, VEGETABLE: 0.12, HERBS: 0.025, SAUCE: 0.02, SUGAR: 0.01 },
  },
  {
    code: 'KHAI-04',
    category: 0,
    name: 'Đậu hũ chiên sả',
    price: 49000,
    description: 'Đậu hũ chiên giòn bên ngoài, mềm bên trong, thơm nhẹ mùi sả.',
    recipe: { TOFU: 0.2, LEMONGRASS: 0.025, OIL: 0.025, SAUCE: 0.01 },
  },
  {
    code: 'CHINH-01',
    category: 1,
    name: 'Cơm tấm sườn nướng',
    price: 79000,
    description: 'Gạo tấm dẻo, sườn heo nướng và rau theo mùa. Một phần ăn trọn vị.',
    recipe: { RICE: 0.15, PORK: 0.2, VEGETABLE: 0.07, SAUCE: 0.025, SUGAR: 0.012 },
  },
  {
    code: 'CHINH-02',
    category: 1,
    name: 'Phở bò tái nạm',
    price: 75000,
    description: 'Bánh phở tươi, thịt bò và nước dùng thơm. Kèm rau thơm.',
    recipe: { PHO: 0.2, BEEF: 0.12, BROTH: 0.4, HERBS: 0.025 },
  },
  {
    code: 'CHINH-03',
    category: 1,
    name: 'Bún chả Hà Nội',
    price: 72000,
    description: 'Thịt heo nướng, bún tươi, rau sống và nước chấm thanh nhẹ.',
    recipe: { PORK: 0.16, NOODLE: 0.2, HERBS: 0.04, SAUCE: 0.025, SUGAR: 0.01 },
  },
  {
    code: 'CHINH-04',
    category: 1,
    name: 'Cơm gà lá chanh',
    price: 85000,
    description: 'Gà mềm thơm lá chanh, cơm nóng và rau ăn kèm.',
    recipe: { CHICKEN: 0.22, RICE: 0.15, LEMONLEAF: 0.005, VEGETABLE: 0.06 },
  },
  {
    code: 'NUONG-01',
    category: 2,
    name: 'Bò nướng sốt tiêu',
    price: 159000,
    description: 'Thịt bò nướng tại bếp, sốt tiêu đen và rau củ. Phần dùng chung.',
    recipe: { BEEF: 0.25, PEPPER: 0.005, VEGETABLE: 0.12, OIL: 0.015 },
  },
  {
    code: 'NUONG-02',
    category: 2,
    name: 'Gà nướng lá chanh',
    price: 139000,
    description: 'Gà ướp thơm, nướng vàng tại bếp, kèm rau và nước chấm.',
    recipe: { CHICKEN: 0.4, LEMONLEAF: 0.008, VEGETABLE: 0.1, SAUCE: 0.025 },
  },
  {
    code: 'NUONG-03',
    category: 2,
    name: 'Tôm nướng sả',
    price: 169000,
    description: 'Tôm nướng cùng sả, rau tươi và nước chấm của bếp.',
    recipe: { SHRIMP: 0.3, LEMONGRASS: 0.03, OIL: 0.015, HERBS: 0.02 },
  },
  {
    code: 'NUONG-04',
    category: 2,
    name: 'Heo nướng mật ong',
    price: 129000,
    description: 'Thịt heo nướng mật ong, vị mặn ngọt cân bằng, phù hợp ăn cùng cơm.',
    recipe: { PORK: 0.3, HONEY: 0.025, SAUCE: 0.02, VEGETABLE: 0.1 },
  },
  {
    code: 'LAU-01',
    category: 3,
    name: 'Lẩu cá rau vườn',
    price: 329000,
    description: 'Nồi lẩu cá, rau theo mùa và bún. Gợi ý cho 2–3 người.',
    recipe: { FISH: 0.5, VEGETABLE: 0.4, NOODLE: 0.35, BROTH: 1.2, HERBS: 0.05 },
  },
  {
    code: 'LAU-02',
    category: 3,
    name: 'Lẩu gà lá é',
    price: 299000,
    description: 'Nước lẩu thanh, thịt gà, nấm và lá é. Gợi ý cho 2–3 người.',
    recipe: { CHICKEN: 0.6, MUSHROOM: 0.15, LEMONLEAF: 0.04, NOODLE: 0.3, BROTH: 1.2 },
  },
  {
    code: 'LAU-03',
    category: 3,
    name: 'Canh nấm đậu hũ',
    price: 69000,
    description: 'Canh nóng với nấm và đậu hũ, dùng nước dùng nền của bếp.',
    recipe: { MUSHROOM: 0.12, TOFU: 0.15, BROTH: 0.5, HERBS: 0.01 },
  },
  {
    code: 'LAU-04',
    category: 3,
    name: 'Canh gà rau củ',
    price: 89000,
    description: 'Thịt gà và rau củ nấu nước dùng thanh nhẹ. Phần dùng chung.',
    recipe: { CHICKEN: 0.2, VEGETABLE: 0.2, BROTH: 0.6 },
  },
  {
    code: 'DRINK-01',
    category: 4,
    name: 'Trà tắc mật ong',
    price: 39000,
    description: 'Trà ô long, tắc tươi và mật ong, pha lạnh tại quầy.',
    recipe: { TEA: 0.008, KUMQUAT: 0.035, HONEY: 0.02 },
  },
  {
    code: 'DRINK-02',
    category: 4,
    name: 'Cà phê sữa đá',
    price: 35000,
    description: 'Cà phê rang xay pha phin, hòa cùng sữa đặc.',
    recipe: { COFFEE: 0.025, MILK: 0.035 },
  },
  {
    code: 'DRINK-03',
    category: 4,
    name: 'Nước sâm nhà nấu',
    price: 29000,
    description: 'Thảo mộc nấu tại quầy, vị ngọt dịu và thanh mát.',
    recipe: { HERBAL: 0.015, SUGAR: 0.018 },
  },
  {
    code: 'DRINK-04',
    category: 4,
    name: 'Trà trái cây',
    price: 45000,
    description: 'Trà ô long với trái cây theo mùa, tươi mát và thơm nhẹ.',
    recipe: { TEA: 0.008, FRUIT: 0.12, SUGAR: 0.015 },
  },
  {
    code: 'DESSERT-01',
    category: 5,
    name: 'Chè khúc bạch',
    price: 49000,
    description: 'Khúc bạch kem sữa, trái cây và hạnh nhân. Có sữa và hạt.',
    recipe: { CREAM: 0.08, GELATIN: 0.005, SUGAR: 0.02, FRUIT: 0.07, ALMOND: 0.01 },
  },
  {
    code: 'DESSERT-02',
    category: 5,
    name: 'Sữa chua trái cây',
    price: 39000,
    description: 'Sữa chua mát lạnh cùng trái cây theo mùa.',
    recipe: { YOGURT: 0.12, FRUIT: 0.1, HONEY: 0.01 },
  },
  {
    code: 'DESSERT-03',
    category: 5,
    name: 'Đĩa trái cây theo mùa',
    price: 59000,
    description: 'Trái cây tươi cắt sẵn, gợi ý chia sẻ sau bữa ăn.',
    recipe: { FRUIT: 0.35 },
  },
  {
    code: 'DESSERT-04',
    category: 5,
    name: 'Pudding sữa',
    price: 45000,
    description: 'Pudding mềm mịn từ sữa và trứng, dùng lạnh.',
    recipe: { MILK: 0.04, CREAM: 0.06, EGG: 1, SUGAR: 0.015 },
  },
];
